name: 'Deploy App to S3'

# on: [push] # toutes les branches
on:

  push:
    branches:

      - pichat # uniquement sur la branche main


jobs:
  deployemen: # non
    runs-on: ubuntu-latest # instance temp
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Install AWS CLI
      run: |
       sudo apt-get update
       sudo apt-get install -y python3-pip
       sudo pip3 install awscli

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key_id ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region eu-west-3


    - name: Check if bucket exists
      run: |
        if aws s3api head-bucket --bucket $AWS_BUCKET_NAME; then
          echo "Bucket exists."
        else
          echo "Bucket does not exist. Stopping the pipeline."
          exit 1
        fi
      env:
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }} 

 
